DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS(
	ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255)
);

INSERT INTO STUDENTS VALUES(1, 'Katerina', 'Yulya');
INSERT INTO STUDENTS VALUES(2, 'Lena', 'Tanya');